### ISSUE TITLE
Prototype - Log In

### ISSUE THREAD

**Issue by SpookySkylark** [bcgov/citz-dst-capstone-2021#138]
#### Log In page Prototype

Create a prototype for basic login page with simple account validation.

#### Tasks
- [x] Create front-end fields
- [ ] Send login information to API
- [ ] Process login information and assign authorization
