### ISSUE TITLE
Handover Documentaion

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#37]
Documentation detailing how to operationalize our proposed application

#### Proposed Outline:
**Solution:**
- [ ] Business Problem
- [ ] User Journeys
- [ ] User research (Clean interview notes)
   - [ ] Pain points identified
    - [ ] process flows
	
**POC and Taking it Forward:**
- [x] Installation guide
- [ ] Frontend
    - [x] Wireframes
    - [x] Flow diagrams
    - [ ] State Diagrams
    - [ ] Technologies
         - [ ] Compilation Steps 
         - [ ] Maintenance Guide
    - [x] Limitations & Considerations
- [x] Database
    - [ ] Data model
    - [ ] Backup & Restore instructions
    - [x] Limitations & Considerations
- [x] API
    - [ ] Technologies
        - [ ] Compilation Steps
        - [ ] Maintenance Guide
    - [ ] CRUD operations & definitions
    - [ ] Limitations & Considerations
- [x] DevOps
    - [x] Deployment guide

#### Nice to Have:
- [ ] Interaction implemented in AdobeXD files
