### ISSUE TITLE
UX/UI Design

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#64]
- [ ] Finish high value wireframes
- [ ] Focus Submitter & Finance Analyst for Sprint 2 _Can't move forward with exec until finance analyst is done_
- [ ] associate screens to stories & personas and prioritize
